### ISSUE TITLE
Customizable MySQL Server settings

### ISSUE THREAD

**Issue by rautamiekka** [licks92/WirelessRedstone#121]
Currently the plugin uses either Bukkit Server's settings or no MySQL at all.

What the config would look like:
```yaml
MySQL:
    enabled: false
    useBukkitSettings: false
    address: localhost
    port: 3306
    username: minecraft
    password: minecraft
```
and the `useSQL` option is replaced by those.
